### PR TITLE
Single video page (basic)

### PR DESCRIPTION
**Pull request by cbh6**
Sorry for the delay, such a busy week :1234: 

I've been testing the website and learning a little how it works. The single video page is working but needs a little of refactor and revision.
I would appreciate if anyone can check the code or modify what needed to get it better. The new functionality is very simple.

### CODE REVIEW

**Comment by sudovijay** [comment]
I was actually planing to do this today lol you beat me to it. anyway it need more work,

-  Design look waayyy basic as you said, it just doesn't have that feel, need to work on that
-  Instead of using title as slug we should use `youtube ID`, that'll be more unique & short at the 
   same time, I know this is more SEO friendly but titles could be duplicate too and they ain't gonna 
   rank anyway as everything is just automated mostly.
-  We need to add click handler on thumb too which takes you to video page
- There are few errors that i did notice while browsing pages like `TypeError: Cannot read property 'id' of null `, probably due to slug not matching, idk need to fix that.
- Duration needs to placed somewhere and fetched too from QUERY as we storing it now.
- Auto loading video on page load ain't a good idea i quess, it'll make things slower for users having slow connection.

@SaraVieira  Sorry if i miss anything,  its 3'morning here lol you're better person to review this 🙂

**Comment by SaraVieira** [comment]
https://awesome-talks-ftztgswqbr.now.sh

**Comment by SaraVieira** [comment]
Hey 👋

Above is the deploy, don't worry about the build ! It's because of it being a fork :)

Awesome thank you for this! It's great work! Open Source is Dope!

About @sudovijay points there are some I want to clear out:

> Instead of using title as slug we should use youtube ID, that'll be more unique & short at the same time, I know this is more SEO friendly

The name of the videos is unique, it's a constrain in the backend, so that you can search and make the slugs this way so I would leave it as it is

> Auto loading video on page load ain't a good idea i quess, it'll make things slower for users having slow connection.

I agree, maybe add the normal Video Component to make it load incrementally like the home page :)

> We need to add click handler on thumb too which takes you to video page

I don't think so, the video page is if you want a better experience and for sharing, the person can still watch from the homepage :)

About the design: It would be dope if we would make the video span 100% of the screen and just take as many height as he wants, also maybe place some more information about the speaker, like their intro and other talks if there are any, I can help with this if you want as it's more queries

Here is an example of one that gives an error: Is JavaScript Making Us Better Professionals?

And don't worry about taking too much time and if you think you don't have time just let me know and I will merge this into a branch here and we can keep working on this togheter 

❤️

**Comment by cbh6** [comment]
I have worked on it a little this morning.

- Fixed the video data query. When video name contains '?' fails due to url. I've added filter contains in the query.
- Added some info about talk's speaker. 

Since I'm not having much more time today I'd appreciate if you could check this and create a branch or something to give the needed styling or code refactor :dango: 

Thanks in advance guys!! :heartbeat: :smile:

**Comment by sudovijay** [comment]
Created a new branch & moved to #95 , Thanks again @cbh6

**Pull request merged**
