### PR TITLE
moved meta tags to Helmet fixes #28

### LINKED ISSUE #28: Add dynamic social media cards
Would be nice to have the speakers page look nice when shared on fb/twitter with the name / photo and maybe description. Not familiar with the Preact ecosystem, is there something like react-helmet to help with this kind of functionality?

### PR DESCRIPTION
**Pull request by alexnm**

### CODE REVIEW

**Comment by SaraVieira** [comment]
I'm going to merge and check if the twitter cards are working !

Thanks alex !

**Comment by SaraVieira** [comment]
If you test the netlify link here: https://cards-dev.twitter.com/validator

You get an error :(

**Comment by alexnm** [comment]
maybe the card validator only looks at the server render? it doesn't recognize the meta tags added via Preact, but when you inspect the page, it looks ok

**Comment by SaraVieira** [comment]
I may have to switch to something like after.js or next! I will tackle this today !

**Comment by SaraVieira** [comment]
Well https://github.com/jaredpalmer/after.js/issues/141 :(

**Comment by SaraVieira** [comment]
GOT IT WOKING WITH AFTER.JS


screen shot 2018-05-28 at 16 53 55

**Comment by tsiq-swyx** [comment]
how was it so easy to move to after.js! wow!

**Comment by SaraVieira** [comment]
Fixed by SSR :D

**Pull request closed without merging**
