### PR TITLE
[WIP]Add a carousel to the category page

### PR DESCRIPTION
**Pull request by pksjce**
Thanks for the invite and the netlify deployment is pretty cool.
Working on #6 here now.
I'm facing some styling issues with the Videos component. Trying to work through that.

### CODE REVIEW

**Comment by pksjce** [comment]
Hey, so this is coming together very nicely. The functionality works good and I'm improving styling
@SaraVieira I have one problem with the slider where I want to show less items in a mobile screen than on a desktop screen. I can do this only in Javascript. How do I detect a mobile device in Javascript?
I found this library. Shall I go ahead and add it? https://github.com/matthewhudson/current-device.

**Comment by SaraVieira** [comment]
Hey!

I see that it's working great! Nice job:)

Yap! Sounds like a solid idea, use it :)

**Comment by tsiq-swyx** [comment]
haha its weird because im now watching this library AND i also just saw this yesterday: http://shouldiuseacarousel.com/

i dont have strong opinions but it was just a funny coincidence

**Comment by varjmes** [comment]
I agree with the website above ^

**Comment by pksjce** [comment]
Actually, the current implementation of carousel is falling short in a lot of ways.
1. No mobile support with the css. Have to do it explicitly in Javscript.
2. Flaky height support, styling it has been quite the challenge and now styling each of the next and prev buttons is not going well.
3. Slow for large lists, no lazyloading.
4. And now as @varjmes suggested, no accessibility support.

My dream of having netflix like carousel with that expanding effect has not worked out. There's seriously a need out there for a decent carousel in React.
I'm thinking I'll discontinue this PR and come back to it later if/when circumstances change.

**Comment by tsiq-swyx** [comment]
its ok! nice try!!

**Pull request closed without merging**
