### PR TITLE
Handle Those Errors ✋

### PR DESCRIPTION
**Pull request by sudovijay**
We actually need to handle all those errors as the page get stuck on loading when there is some unhandled error probably due to SSR

- [x]  Handle 404 error page
- [x] Handle wrong Slug in speakers
- [x] Handle wrong Slug in tags

### CODE REVIEW

**Comment by sudovijay** [comment]
and im done 😎

**Comment by SaraVieira** [comment]
Just removed the header for the the tag when it doesn't exist and looks great 🗡 


YOU ARE THE BEST

**Comment by sudovijay** [comment]
nowhere near to best!!  anyway missed that header thingy, i was in a wrong flow i quess .

**Comment by SaraVieira** [comment]
The design skills are doping up tho! Both this and the banner look awesome!

**Comment by sudovijay** [comment]
my design skills? lol i don't even remember having that skill . it just baddddddddd !! and its something i can't do much about it,  not a creative person. just not my thingy ..

**Comment by SaraVieira** [comment]
Valid !

**Pull request merged**
