### PR TITLE
Adding Some cookies 🍪

### PR DESCRIPTION
**Pull request by sudovijay**
Did set cookie expiry to 365 Days, I quess that'll be more than enough.

### CODE REVIEW

**Comment by SaraVieira** [comment]
Duuude this is awesome !

**Comment by SaraVieira** [comment]
We need the banner tho :(

**Comment by sudovijay** [comment]
Work in progress, making one. trying to avoid any more lib, lets see otherwise gonna use React Cookie Banner lol

**Comment by SaraVieira** [comment]
Let me know when you add it so I can make a new release :D

**Comment by sudovijay** [comment]
@SaraVieira  its all yours now 🙂

**Comment by SaraVieira** [comment]
@sudovijay I think the  banner should only appear on the client otherwise we get the flash even if we already saw it :(

**Comment by SaraVieira** [comment]
Fixed the flash and I am just going to wait for the ckecks to merge and deploy :D

**Comment by sudovijay** [comment]
opps, forget about it, we dealing with some SSR here lol

**Comment by sudovijay** [comment]
thats a clever fix 👏

**Comment by SaraVieira** [comment]
clever means hacky and I like it ahah

**Comment by sudovijay** [comment]
not exactly hacky, if it works its all valid / clever :)

**Comment by SaraVieira** [comment]
Merged and deployed ! https://awesometalks.party/


Pretend I said thanks and you got mad ahah

I shall tweet about this after dinner :D

**Pull request merged**
